### ISSUE TITLE
json api

### ISSUE THREAD

**Issue by asottile** [chriskuehl/dumb-pypi#28]
I haven't looked into this all that much and I'm not sure if it's specced somewhere but I'd like to programmatically query the packages (in my particular usecase for mtimes).

The new pypi.org has an advertised json api so maybe we could mimic that (or implement some static subset of it) which would satisfy my usecase.  Failing that, I could always just parse the simple page, though I'd like to avoid that if possible :D

I can work on a PR for this as well, just want to figure out what scope to target here and make sure this is a good idea

**Comment by chriskuehl** [comment]
I think this is great.

I've been wanting (and people have been asking for at $JOB) some interface to query details about packages, but I've been hesitant to add anything because I wasn't crazy about adding an interface specific to dumb-pypi which people would start depending on (I remember this bit us when we migrated from pypicloud where people were depending on its JSON API (which was actually only intended for AJAX calls from its web interface, lol)).

Do you know if https://warehouse.pypa.io/api-reference/json/ the right resource for the API? For some reason I thought they had implemented way more than these two endpoints (and even some stuff like searching that we probably can't do with dumb-pypi).

Some example output:

* https://pypi.org/pypi/dumb-pypi/json: https://i.fluffy.cc/CJQKF1kJ5lBWWxHV59CTTw4LttQ3V5v0.html (formatted)
* I tried https://pypi.org/pypi/dumb-pypi/1.2.1/json but it returns the same content despite only asking for one version? The docs seem to indicate it should return only data about the one version...

At least to start with, it will be hard to provide all of these keys (like the classifiers and other stuff from `setup.py`), but easy to return a subset (like the version information) which could still be very useful.

**Comment by asottile** [comment]
Their api is a little bit weird, the versioned endpoint returns at the top level info for that version, but also includes a `releases` section that contains all the other information as well?

And yeah, warehouse seems to be the canonical implementation of pypi so we should go with what they are doing.

Definitely agree that dumb-pypi can't (and shouldn't) implement the full json api, though something that lists releases (and whatever information it can) would be a big improvement over the (clunky) querying via the simple pages.
